Add Reducers and Actions
BHObserver/bookstore pull request #4
Opened 2023-10-05 15:29 UTC by BHObserver

### In this branch

- **Redux is used for scaling**

2023-10-05 16:11 UTC, Johnadibe requested changes
# STATUS: REQUIRED CHANGES ♻️
### Hi @BHObserver👋🏽, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Highlights
✅ You used GitFlow correctly 👍🏽
✅ Linter checks passed✔️
✅ Added Redux Toolkit✔
✅ Created a directory that will contain all your Redux logic✔
✅ Configured a Redux store✔
✅ Defined a slice of state for books✔
✅ Defined a slice of state for categories✔


## Required Changes ♻️

> - [ ] Please revise your README file to ensure that the Project name, description, and setup section accurately reflect the current project.👍
> 
> ![1](https://github.com/BHObserver/bookstore/assets/40009354/66ebacd9-fbc5-4765-a84b-da5e34b2f4f7)
> 
> ![2](https://github.com/BHObserver/bookstore/assets/40009354/e381d556-688d-403b-ae30-a74460066e2f)

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-05 16:11 UTC, Johnadibe commented on src/redux/categories/categoriesSlice.js
> +  },
> - [ ] According to the project requirements as stated [here](https://github.com/microverseinc/curriculum-react-redux/blob/main/bookstore/add_reducers_an_actions_v2.md#:~:text=Includes%20a%20reducer%20that%20checks%20the%20status%20and%20always%20returns%20%22Under%20construction%22%20(the%20initial%20state%20should%20check%20to%20that%20string)), you should include a reducer that checks the status and always returns "Under construction". Please note that there is no need to create reducers for addCategory and removeCategory as per the project's instructions. It's crucial to align with the project's requirements for better results. This will be beneficial in accomplishing the task.👍
> 
> You can use the below as a guide:
> 
> ```
> reducers: {
>     checkStatus: (state, action) => {
>       state.categories =
>         action.payload === "Under construction"
>           ? "Under construction"
>           : state.categories
>     },
>   }
> 
> ```

2023-10-05 18:34 UTC, Cabraham1 approved these changes
Hi @BHObserver , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media1.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif"/>

## Highlights

📌 implemented all required changes ✅


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-05 18:49 UTC, merged

2023-10-09 15:39 UTC, TuyishimireEric commented
# Status: APPROVED 🟢  
### Hi  @BHObserver 👋 👋 

#### I'm @TuyishimireEric, Your code reviewer,
Good job on implementing the project requirements! 🥇 
![done](https://media.giphy.com/media/l1uga8ObPBnIBoXUQ/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it 🦾  
Congratulations! 🎉


## Highlight 👍 
✅ implemented all required changes  👍 

### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/enus/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).